spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
      spring.json.value.default.type: com.personal-data-service.UserProfileUpdatedEvent

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://your-keycloak-domain/realms/allstate-realm
          # OR use jwk-set-uri if issuer discovery is not working:
          # jwk-set-uri: https://your-keycloak-domain/realms/allstate-realm/protocol/openid-connect/certs

  resilience4j:
    circuitbreaker:
      instances:
        redis:
          registerHealthIndicator: true
          slidingWindowSize: 10
          failureRateThreshold: 50
          waitDurationInOpenState: 5s
          permittedNumberOfCallsInHalfOpenState: 3
          minimumNumberOfCalls: 5
        email:
          registerHealthIndicator: true
          slidingWindowSize: 10
          failureRateThreshold: 50
          waitDurationInOpenState: 5s
          permittedNumberOfCallsInHalfOpenState: 3
          minimumNumberOfCalls: 5

  datasource:
    url: jdbc:postgresql://localhost:5432/personal_info_migration
    username: postgres
    password: Test2323
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true