/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.allstate.personal_data_service.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NotificationEmailAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2756072181765360241L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NotificationEmailAvro\",\"namespace\":\"com.allstate.personal_data_service.avro\",\"fields\":[{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"wantsPromotions\",\"type\":\"boolean\"},{\"name\":\"locale\",\"type\":\"string\",\"default\":\"en_US\"},{\"name\":\"templateId\",\"type\":\"string\",\"default\":\"DEFAULT_TEMPLATE\"},{\"name\":\"timestamp\",\"type\":\"long\",\"default\":0},{\"name\":\"eventSource\",\"type\":\"string\",\"default\":\"personal_information_service\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NotificationEmailAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NotificationEmailAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NotificationEmailAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NotificationEmailAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NotificationEmailAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NotificationEmailAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NotificationEmailAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NotificationEmailAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NotificationEmailAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence firstName;
  private java.lang.CharSequence email;
  private boolean wantsPromotions;
  private java.lang.CharSequence locale;
  private java.lang.CharSequence templateId;
  private long timestamp;
  private java.lang.CharSequence eventSource;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NotificationEmailAvro() {}

  /**
   * All-args constructor.
   * @param firstName The new value for firstName
   * @param email The new value for email
   * @param wantsPromotions The new value for wantsPromotions
   * @param locale The new value for locale
   * @param templateId The new value for templateId
   * @param timestamp The new value for timestamp
   * @param eventSource The new value for eventSource
   */
  public NotificationEmailAvro(java.lang.CharSequence firstName, java.lang.CharSequence email, java.lang.Boolean wantsPromotions, java.lang.CharSequence locale, java.lang.CharSequence templateId, java.lang.Long timestamp, java.lang.CharSequence eventSource) {
    this.firstName = firstName;
    this.email = email;
    this.wantsPromotions = wantsPromotions;
    this.locale = locale;
    this.templateId = templateId;
    this.timestamp = timestamp;
    this.eventSource = eventSource;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return firstName;
    case 1: return email;
    case 2: return wantsPromotions;
    case 3: return locale;
    case 4: return templateId;
    case 5: return timestamp;
    case 6: return eventSource;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: firstName = (java.lang.CharSequence)value$; break;
    case 1: email = (java.lang.CharSequence)value$; break;
    case 2: wantsPromotions = (java.lang.Boolean)value$; break;
    case 3: locale = (java.lang.CharSequence)value$; break;
    case 4: templateId = (java.lang.CharSequence)value$; break;
    case 5: timestamp = (java.lang.Long)value$; break;
    case 6: eventSource = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }


  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'wantsPromotions' field.
   * @return The value of the 'wantsPromotions' field.
   */
  public boolean getWantsPromotions() {
    return wantsPromotions;
  }


  /**
   * Sets the value of the 'wantsPromotions' field.
   * @param value the value to set.
   */
  public void setWantsPromotions(boolean value) {
    this.wantsPromotions = value;
  }

  /**
   * Gets the value of the 'locale' field.
   * @return The value of the 'locale' field.
   */
  public java.lang.CharSequence getLocale() {
    return locale;
  }


  /**
   * Sets the value of the 'locale' field.
   * @param value the value to set.
   */
  public void setLocale(java.lang.CharSequence value) {
    this.locale = value;
  }

  /**
   * Gets the value of the 'templateId' field.
   * @return The value of the 'templateId' field.
   */
  public java.lang.CharSequence getTemplateId() {
    return templateId;
  }


  /**
   * Sets the value of the 'templateId' field.
   * @param value the value to set.
   */
  public void setTemplateId(java.lang.CharSequence value) {
    this.templateId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'eventSource' field.
   * @return The value of the 'eventSource' field.
   */
  public java.lang.CharSequence getEventSource() {
    return eventSource;
  }


  /**
   * Sets the value of the 'eventSource' field.
   * @param value the value to set.
   */
  public void setEventSource(java.lang.CharSequence value) {
    this.eventSource = value;
  }

  /**
   * Creates a new NotificationEmailAvro RecordBuilder.
   * @return A new NotificationEmailAvro RecordBuilder
   */
  public static com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder newBuilder() {
    return new com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder();
  }

  /**
   * Creates a new NotificationEmailAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NotificationEmailAvro RecordBuilder
   */
  public static com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder newBuilder(com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder other) {
    if (other == null) {
      return new com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder();
    } else {
      return new com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder(other);
    }
  }

  /**
   * Creates a new NotificationEmailAvro RecordBuilder by copying an existing NotificationEmailAvro instance.
   * @param other The existing instance to copy.
   * @return A new NotificationEmailAvro RecordBuilder
   */
  public static com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder newBuilder(com.allstate.personal_data_service.avro.NotificationEmailAvro other) {
    if (other == null) {
      return new com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder();
    } else {
      return new com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for NotificationEmailAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NotificationEmailAvro>
    implements org.apache.avro.data.RecordBuilder<NotificationEmailAvro> {

    private java.lang.CharSequence firstName;
    private java.lang.CharSequence email;
    private boolean wantsPromotions;
    private java.lang.CharSequence locale;
    private java.lang.CharSequence templateId;
    private long timestamp;
    private java.lang.CharSequence eventSource;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.wantsPromotions)) {
        this.wantsPromotions = data().deepCopy(fields()[2].schema(), other.wantsPromotions);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.locale)) {
        this.locale = data().deepCopy(fields()[3].schema(), other.locale);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.templateId)) {
        this.templateId = data().deepCopy(fields()[4].schema(), other.templateId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.eventSource)) {
        this.eventSource = data().deepCopy(fields()[6].schema(), other.eventSource);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing NotificationEmailAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.allstate.personal_data_service.avro.NotificationEmailAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.firstName)) {
        this.firstName = data().deepCopy(fields()[0].schema(), other.firstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.wantsPromotions)) {
        this.wantsPromotions = data().deepCopy(fields()[2].schema(), other.wantsPromotions);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.locale)) {
        this.locale = data().deepCopy(fields()[3].schema(), other.locale);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.templateId)) {
        this.templateId = data().deepCopy(fields()[4].schema(), other.templateId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.eventSource)) {
        this.eventSource = data().deepCopy(fields()[6].schema(), other.eventSource);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }


    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.firstName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.email = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder clearEmail() {
      email = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'wantsPromotions' field.
      * @return The value.
      */
    public boolean getWantsPromotions() {
      return wantsPromotions;
    }


    /**
      * Sets the value of the 'wantsPromotions' field.
      * @param value The value of 'wantsPromotions'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder setWantsPromotions(boolean value) {
      validate(fields()[2], value);
      this.wantsPromotions = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'wantsPromotions' field has been set.
      * @return True if the 'wantsPromotions' field has been set, false otherwise.
      */
    public boolean hasWantsPromotions() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'wantsPromotions' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder clearWantsPromotions() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'locale' field.
      * @return The value.
      */
    public java.lang.CharSequence getLocale() {
      return locale;
    }


    /**
      * Sets the value of the 'locale' field.
      * @param value The value of 'locale'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder setLocale(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.locale = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'locale' field has been set.
      * @return True if the 'locale' field has been set, false otherwise.
      */
    public boolean hasLocale() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'locale' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder clearLocale() {
      locale = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'templateId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTemplateId() {
      return templateId;
    }


    /**
      * Sets the value of the 'templateId' field.
      * @param value The value of 'templateId'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder setTemplateId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.templateId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'templateId' field has been set.
      * @return True if the 'templateId' field has been set, false otherwise.
      */
    public boolean hasTemplateId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'templateId' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder clearTemplateId() {
      templateId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder setTimestamp(long value) {
      validate(fields()[5], value);
      this.timestamp = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder clearTimestamp() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventSource' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventSource() {
      return eventSource;
    }


    /**
      * Sets the value of the 'eventSource' field.
      * @param value The value of 'eventSource'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder setEventSource(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.eventSource = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'eventSource' field has been set.
      * @return True if the 'eventSource' field has been set, false otherwise.
      */
    public boolean hasEventSource() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'eventSource' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.NotificationEmailAvro.Builder clearEventSource() {
      eventSource = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NotificationEmailAvro build() {
      try {
        NotificationEmailAvro record = new NotificationEmailAvro();
        record.firstName = fieldSetFlags()[0] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.email = fieldSetFlags()[1] ? this.email : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.wantsPromotions = fieldSetFlags()[2] ? this.wantsPromotions : (java.lang.Boolean) defaultValue(fields()[2]);
        record.locale = fieldSetFlags()[3] ? this.locale : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.templateId = fieldSetFlags()[4] ? this.templateId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.timestamp = fieldSetFlags()[5] ? this.timestamp : (java.lang.Long) defaultValue(fields()[5]);
        record.eventSource = fieldSetFlags()[6] ? this.eventSource : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NotificationEmailAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<NotificationEmailAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NotificationEmailAvro>
    READER$ = (org.apache.avro.io.DatumReader<NotificationEmailAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.firstName);

    out.writeString(this.email);

    out.writeBoolean(this.wantsPromotions);

    out.writeString(this.locale);

    out.writeString(this.templateId);

    out.writeLong(this.timestamp);

    out.writeString(this.eventSource);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      this.wantsPromotions = in.readBoolean();

      this.locale = in.readString(this.locale instanceof Utf8 ? (Utf8)this.locale : null);

      this.templateId = in.readString(this.templateId instanceof Utf8 ? (Utf8)this.templateId : null);

      this.timestamp = in.readLong();

      this.eventSource = in.readString(this.eventSource instanceof Utf8 ? (Utf8)this.eventSource : null);

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);
          break;

        case 1:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 2:
          this.wantsPromotions = in.readBoolean();
          break;

        case 3:
          this.locale = in.readString(this.locale instanceof Utf8 ? (Utf8)this.locale : null);
          break;

        case 4:
          this.templateId = in.readString(this.templateId instanceof Utf8 ? (Utf8)this.templateId : null);
          break;

        case 5:
          this.timestamp = in.readLong();
          break;

        case 6:
          this.eventSource = in.readString(this.eventSource instanceof Utf8 ? (Utf8)this.eventSource : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










