/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.allstate.personal_data_service.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SensitiveFieldUpdatedAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4567400559559393407L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SensitiveFieldUpdatedAvro\",\"namespace\":\"com.allstate.personal_data_service.avro\",\"fields\":[{\"name\":\"userId\",\"type\":\"long\"},{\"name\":\"fieldName\",\"type\":\"string\"},{\"name\":\"oldValue\",\"type\":\"string\"},{\"name\":\"newValue\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\",\"default\":0},{\"name\":\"updatedByService\",\"type\":\"string\",\"default\":\"personal_information_service\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SensitiveFieldUpdatedAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SensitiveFieldUpdatedAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SensitiveFieldUpdatedAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SensitiveFieldUpdatedAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SensitiveFieldUpdatedAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SensitiveFieldUpdatedAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SensitiveFieldUpdatedAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SensitiveFieldUpdatedAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SensitiveFieldUpdatedAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long userId;
  private java.lang.CharSequence fieldName;
  private java.lang.CharSequence oldValue;
  private java.lang.CharSequence newValue;
  private long timestamp;
  private java.lang.CharSequence updatedByService;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SensitiveFieldUpdatedAvro() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param fieldName The new value for fieldName
   * @param oldValue The new value for oldValue
   * @param newValue The new value for newValue
   * @param timestamp The new value for timestamp
   * @param updatedByService The new value for updatedByService
   */
  public SensitiveFieldUpdatedAvro(java.lang.Long userId, java.lang.CharSequence fieldName, java.lang.CharSequence oldValue, java.lang.CharSequence newValue, java.lang.Long timestamp, java.lang.CharSequence updatedByService) {
    this.userId = userId;
    this.fieldName = fieldName;
    this.oldValue = oldValue;
    this.newValue = newValue;
    this.timestamp = timestamp;
    this.updatedByService = updatedByService;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return fieldName;
    case 2: return oldValue;
    case 3: return newValue;
    case 4: return timestamp;
    case 5: return updatedByService;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.Long)value$; break;
    case 1: fieldName = (java.lang.CharSequence)value$; break;
    case 2: oldValue = (java.lang.CharSequence)value$; break;
    case 3: newValue = (java.lang.CharSequence)value$; break;
    case 4: timestamp = (java.lang.Long)value$; break;
    case 5: updatedByService = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public long getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(long value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'fieldName' field.
   * @return The value of the 'fieldName' field.
   */
  public java.lang.CharSequence getFieldName() {
    return fieldName;
  }


  /**
   * Sets the value of the 'fieldName' field.
   * @param value the value to set.
   */
  public void setFieldName(java.lang.CharSequence value) {
    this.fieldName = value;
  }

  /**
   * Gets the value of the 'oldValue' field.
   * @return The value of the 'oldValue' field.
   */
  public java.lang.CharSequence getOldValue() {
    return oldValue;
  }


  /**
   * Sets the value of the 'oldValue' field.
   * @param value the value to set.
   */
  public void setOldValue(java.lang.CharSequence value) {
    this.oldValue = value;
  }

  /**
   * Gets the value of the 'newValue' field.
   * @return The value of the 'newValue' field.
   */
  public java.lang.CharSequence getNewValue() {
    return newValue;
  }


  /**
   * Sets the value of the 'newValue' field.
   * @param value the value to set.
   */
  public void setNewValue(java.lang.CharSequence value) {
    this.newValue = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'updatedByService' field.
   * @return The value of the 'updatedByService' field.
   */
  public java.lang.CharSequence getUpdatedByService() {
    return updatedByService;
  }


  /**
   * Sets the value of the 'updatedByService' field.
   * @param value the value to set.
   */
  public void setUpdatedByService(java.lang.CharSequence value) {
    this.updatedByService = value;
  }

  /**
   * Creates a new SensitiveFieldUpdatedAvro RecordBuilder.
   * @return A new SensitiveFieldUpdatedAvro RecordBuilder
   */
  public static com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder newBuilder() {
    return new com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder();
  }

  /**
   * Creates a new SensitiveFieldUpdatedAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SensitiveFieldUpdatedAvro RecordBuilder
   */
  public static com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder newBuilder(com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder other) {
    if (other == null) {
      return new com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder();
    } else {
      return new com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder(other);
    }
  }

  /**
   * Creates a new SensitiveFieldUpdatedAvro RecordBuilder by copying an existing SensitiveFieldUpdatedAvro instance.
   * @param other The existing instance to copy.
   * @return A new SensitiveFieldUpdatedAvro RecordBuilder
   */
  public static com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder newBuilder(com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro other) {
    if (other == null) {
      return new com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder();
    } else {
      return new com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for SensitiveFieldUpdatedAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SensitiveFieldUpdatedAvro>
    implements org.apache.avro.data.RecordBuilder<SensitiveFieldUpdatedAvro> {

    private long userId;
    private java.lang.CharSequence fieldName;
    private java.lang.CharSequence oldValue;
    private java.lang.CharSequence newValue;
    private long timestamp;
    private java.lang.CharSequence updatedByService;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.fieldName)) {
        this.fieldName = data().deepCopy(fields()[1].schema(), other.fieldName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.oldValue)) {
        this.oldValue = data().deepCopy(fields()[2].schema(), other.oldValue);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.newValue)) {
        this.newValue = data().deepCopy(fields()[3].schema(), other.newValue);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.updatedByService)) {
        this.updatedByService = data().deepCopy(fields()[5].schema(), other.updatedByService);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing SensitiveFieldUpdatedAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fieldName)) {
        this.fieldName = data().deepCopy(fields()[1].schema(), other.fieldName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.oldValue)) {
        this.oldValue = data().deepCopy(fields()[2].schema(), other.oldValue);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.newValue)) {
        this.newValue = data().deepCopy(fields()[3].schema(), other.newValue);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.updatedByService)) {
        this.updatedByService = data().deepCopy(fields()[5].schema(), other.updatedByService);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public long getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder setUserId(long value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'fieldName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFieldName() {
      return fieldName;
    }


    /**
      * Sets the value of the 'fieldName' field.
      * @param value The value of 'fieldName'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder setFieldName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.fieldName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'fieldName' field has been set.
      * @return True if the 'fieldName' field has been set, false otherwise.
      */
    public boolean hasFieldName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'fieldName' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder clearFieldName() {
      fieldName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'oldValue' field.
      * @return The value.
      */
    public java.lang.CharSequence getOldValue() {
      return oldValue;
    }


    /**
      * Sets the value of the 'oldValue' field.
      * @param value The value of 'oldValue'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder setOldValue(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.oldValue = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'oldValue' field has been set.
      * @return True if the 'oldValue' field has been set, false otherwise.
      */
    public boolean hasOldValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'oldValue' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder clearOldValue() {
      oldValue = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'newValue' field.
      * @return The value.
      */
    public java.lang.CharSequence getNewValue() {
      return newValue;
    }


    /**
      * Sets the value of the 'newValue' field.
      * @param value The value of 'newValue'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder setNewValue(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.newValue = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'newValue' field has been set.
      * @return True if the 'newValue' field has been set, false otherwise.
      */
    public boolean hasNewValue() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'newValue' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder clearNewValue() {
      newValue = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder setTimestamp(long value) {
      validate(fields()[4], value);
      this.timestamp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder clearTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedByService' field.
      * @return The value.
      */
    public java.lang.CharSequence getUpdatedByService() {
      return updatedByService;
    }


    /**
      * Sets the value of the 'updatedByService' field.
      * @param value The value of 'updatedByService'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder setUpdatedByService(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.updatedByService = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedByService' field has been set.
      * @return True if the 'updatedByService' field has been set, false otherwise.
      */
    public boolean hasUpdatedByService() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'updatedByService' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.SensitiveFieldUpdatedAvro.Builder clearUpdatedByService() {
      updatedByService = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SensitiveFieldUpdatedAvro build() {
      try {
        SensitiveFieldUpdatedAvro record = new SensitiveFieldUpdatedAvro();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.Long) defaultValue(fields()[0]);
        record.fieldName = fieldSetFlags()[1] ? this.fieldName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.oldValue = fieldSetFlags()[2] ? this.oldValue : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.newValue = fieldSetFlags()[3] ? this.newValue : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.timestamp = fieldSetFlags()[4] ? this.timestamp : (java.lang.Long) defaultValue(fields()[4]);
        record.updatedByService = fieldSetFlags()[5] ? this.updatedByService : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SensitiveFieldUpdatedAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<SensitiveFieldUpdatedAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SensitiveFieldUpdatedAvro>
    READER$ = (org.apache.avro.io.DatumReader<SensitiveFieldUpdatedAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.userId);

    out.writeString(this.fieldName);

    out.writeString(this.oldValue);

    out.writeString(this.newValue);

    out.writeLong(this.timestamp);

    out.writeString(this.updatedByService);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readLong();

      this.fieldName = in.readString(this.fieldName instanceof Utf8 ? (Utf8)this.fieldName : null);

      this.oldValue = in.readString(this.oldValue instanceof Utf8 ? (Utf8)this.oldValue : null);

      this.newValue = in.readString(this.newValue instanceof Utf8 ? (Utf8)this.newValue : null);

      this.timestamp = in.readLong();

      this.updatedByService = in.readString(this.updatedByService instanceof Utf8 ? (Utf8)this.updatedByService : null);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readLong();
          break;

        case 1:
          this.fieldName = in.readString(this.fieldName instanceof Utf8 ? (Utf8)this.fieldName : null);
          break;

        case 2:
          this.oldValue = in.readString(this.oldValue instanceof Utf8 ? (Utf8)this.oldValue : null);
          break;

        case 3:
          this.newValue = in.readString(this.newValue instanceof Utf8 ? (Utf8)this.newValue : null);
          break;

        case 4:
          this.timestamp = in.readLong();
          break;

        case 5:
          this.updatedByService = in.readString(this.updatedByService instanceof Utf8 ? (Utf8)this.updatedByService : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










