/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.allstate.personal_data_service.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserProfileUpdatedAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7544771004558190061L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserProfileUpdatedAvro\",\"namespace\":\"com.allstate.personal_data_service.avro\",\"fields\":[{\"name\":\"userId\",\"type\":\"long\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"phoneNumber\",\"type\":\"string\"},{\"name\":\"wantsPromotions\",\"type\":\"boolean\"},{\"name\":\"locale\",\"type\":\"string\"},{\"name\":\"address\",\"type\":{\"type\":\"record\",\"name\":\"AddressAvro\",\"fields\":[{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"zipCode\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserProfileUpdatedAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserProfileUpdatedAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserProfileUpdatedAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserProfileUpdatedAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserProfileUpdatedAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserProfileUpdatedAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserProfileUpdatedAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserProfileUpdatedAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserProfileUpdatedAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long userId;
  private java.lang.CharSequence firstName;
  private java.lang.CharSequence lastName;
  private java.lang.CharSequence email;
  private java.lang.CharSequence phoneNumber;
  private boolean wantsPromotions;
  private java.lang.CharSequence locale;
  private com.allstate.personal_data_service.avro.AddressAvro address;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserProfileUpdatedAvro() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param firstName The new value for firstName
   * @param lastName The new value for lastName
   * @param email The new value for email
   * @param phoneNumber The new value for phoneNumber
   * @param wantsPromotions The new value for wantsPromotions
   * @param locale The new value for locale
   * @param address The new value for address
   */
  public UserProfileUpdatedAvro(java.lang.Long userId, java.lang.CharSequence firstName, java.lang.CharSequence lastName, java.lang.CharSequence email, java.lang.CharSequence phoneNumber, java.lang.Boolean wantsPromotions, java.lang.CharSequence locale, com.allstate.personal_data_service.avro.AddressAvro address) {
    this.userId = userId;
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
    this.phoneNumber = phoneNumber;
    this.wantsPromotions = wantsPromotions;
    this.locale = locale;
    this.address = address;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return firstName;
    case 2: return lastName;
    case 3: return email;
    case 4: return phoneNumber;
    case 5: return wantsPromotions;
    case 6: return locale;
    case 7: return address;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.Long)value$; break;
    case 1: firstName = (java.lang.CharSequence)value$; break;
    case 2: lastName = (java.lang.CharSequence)value$; break;
    case 3: email = (java.lang.CharSequence)value$; break;
    case 4: phoneNumber = (java.lang.CharSequence)value$; break;
    case 5: wantsPromotions = (java.lang.Boolean)value$; break;
    case 6: locale = (java.lang.CharSequence)value$; break;
    case 7: address = (com.allstate.personal_data_service.avro.AddressAvro)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public long getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(long value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }


  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }


  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'phoneNumber' field.
   * @return The value of the 'phoneNumber' field.
   */
  public java.lang.CharSequence getPhoneNumber() {
    return phoneNumber;
  }


  /**
   * Sets the value of the 'phoneNumber' field.
   * @param value the value to set.
   */
  public void setPhoneNumber(java.lang.CharSequence value) {
    this.phoneNumber = value;
  }

  /**
   * Gets the value of the 'wantsPromotions' field.
   * @return The value of the 'wantsPromotions' field.
   */
  public boolean getWantsPromotions() {
    return wantsPromotions;
  }


  /**
   * Sets the value of the 'wantsPromotions' field.
   * @param value the value to set.
   */
  public void setWantsPromotions(boolean value) {
    this.wantsPromotions = value;
  }

  /**
   * Gets the value of the 'locale' field.
   * @return The value of the 'locale' field.
   */
  public java.lang.CharSequence getLocale() {
    return locale;
  }


  /**
   * Sets the value of the 'locale' field.
   * @param value the value to set.
   */
  public void setLocale(java.lang.CharSequence value) {
    this.locale = value;
  }

  /**
   * Gets the value of the 'address' field.
   * @return The value of the 'address' field.
   */
  public com.allstate.personal_data_service.avro.AddressAvro getAddress() {
    return address;
  }


  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(com.allstate.personal_data_service.avro.AddressAvro value) {
    this.address = value;
  }

  /**
   * Creates a new UserProfileUpdatedAvro RecordBuilder.
   * @return A new UserProfileUpdatedAvro RecordBuilder
   */
  public static com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder newBuilder() {
    return new com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder();
  }

  /**
   * Creates a new UserProfileUpdatedAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserProfileUpdatedAvro RecordBuilder
   */
  public static com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder newBuilder(com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder other) {
    if (other == null) {
      return new com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder();
    } else {
      return new com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder(other);
    }
  }

  /**
   * Creates a new UserProfileUpdatedAvro RecordBuilder by copying an existing UserProfileUpdatedAvro instance.
   * @param other The existing instance to copy.
   * @return A new UserProfileUpdatedAvro RecordBuilder
   */
  public static com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder newBuilder(com.allstate.personal_data_service.avro.UserProfileUpdatedAvro other) {
    if (other == null) {
      return new com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder();
    } else {
      return new com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserProfileUpdatedAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserProfileUpdatedAvro>
    implements org.apache.avro.data.RecordBuilder<UserProfileUpdatedAvro> {

    private long userId;
    private java.lang.CharSequence firstName;
    private java.lang.CharSequence lastName;
    private java.lang.CharSequence email;
    private java.lang.CharSequence phoneNumber;
    private boolean wantsPromotions;
    private java.lang.CharSequence locale;
    private com.allstate.personal_data_service.avro.AddressAvro address;
    private com.allstate.personal_data_service.avro.AddressAvro.Builder addressBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.firstName)) {
        this.firstName = data().deepCopy(fields()[1].schema(), other.firstName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[4].schema(), other.phoneNumber);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.wantsPromotions)) {
        this.wantsPromotions = data().deepCopy(fields()[5].schema(), other.wantsPromotions);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.locale)) {
        this.locale = data().deepCopy(fields()[6].schema(), other.locale);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.address)) {
        this.address = data().deepCopy(fields()[7].schema(), other.address);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (other.hasAddressBuilder()) {
        this.addressBuilder = com.allstate.personal_data_service.avro.AddressAvro.newBuilder(other.getAddressBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing UserProfileUpdatedAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.allstate.personal_data_service.avro.UserProfileUpdatedAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.firstName)) {
        this.firstName = data().deepCopy(fields()[1].schema(), other.firstName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastName)) {
        this.lastName = data().deepCopy(fields()[2].schema(), other.lastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.email)) {
        this.email = data().deepCopy(fields()[3].schema(), other.email);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[4].schema(), other.phoneNumber);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.wantsPromotions)) {
        this.wantsPromotions = data().deepCopy(fields()[5].schema(), other.wantsPromotions);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.locale)) {
        this.locale = data().deepCopy(fields()[6].schema(), other.locale);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.address)) {
        this.address = data().deepCopy(fields()[7].schema(), other.address);
        fieldSetFlags()[7] = true;
      }
      this.addressBuilder = null;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public long getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder setUserId(long value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }


    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.firstName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }


    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.lastName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.email = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder clearEmail() {
      email = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'phoneNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhoneNumber() {
      return phoneNumber;
    }


    /**
      * Sets the value of the 'phoneNumber' field.
      * @param value The value of 'phoneNumber'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder setPhoneNumber(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.phoneNumber = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'phoneNumber' field has been set.
      * @return True if the 'phoneNumber' field has been set, false otherwise.
      */
    public boolean hasPhoneNumber() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'phoneNumber' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder clearPhoneNumber() {
      phoneNumber = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'wantsPromotions' field.
      * @return The value.
      */
    public boolean getWantsPromotions() {
      return wantsPromotions;
    }


    /**
      * Sets the value of the 'wantsPromotions' field.
      * @param value The value of 'wantsPromotions'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder setWantsPromotions(boolean value) {
      validate(fields()[5], value);
      this.wantsPromotions = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'wantsPromotions' field has been set.
      * @return True if the 'wantsPromotions' field has been set, false otherwise.
      */
    public boolean hasWantsPromotions() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'wantsPromotions' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder clearWantsPromotions() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'locale' field.
      * @return The value.
      */
    public java.lang.CharSequence getLocale() {
      return locale;
    }


    /**
      * Sets the value of the 'locale' field.
      * @param value The value of 'locale'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder setLocale(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.locale = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'locale' field has been set.
      * @return True if the 'locale' field has been set, false otherwise.
      */
    public boolean hasLocale() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'locale' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder clearLocale() {
      locale = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public com.allstate.personal_data_service.avro.AddressAvro getAddress() {
      return address;
    }


    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder setAddress(com.allstate.personal_data_service.avro.AddressAvro value) {
      validate(fields()[7], value);
      this.addressBuilder = null;
      this.address = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[7];
    }

    /**
     * Gets the Builder instance for the 'address' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.allstate.personal_data_service.avro.AddressAvro.Builder getAddressBuilder() {
      if (addressBuilder == null) {
        if (hasAddress()) {
          setAddressBuilder(com.allstate.personal_data_service.avro.AddressAvro.newBuilder(address));
        } else {
          setAddressBuilder(com.allstate.personal_data_service.avro.AddressAvro.newBuilder());
        }
      }
      return addressBuilder;
    }

    /**
     * Sets the Builder instance for the 'address' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder setAddressBuilder(com.allstate.personal_data_service.avro.AddressAvro.Builder value) {
      clearAddress();
      addressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'address' field has an active Builder instance
     * @return True if the 'address' field has an active Builder instance
     */
    public boolean hasAddressBuilder() {
      return addressBuilder != null;
    }

    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public com.allstate.personal_data_service.avro.UserProfileUpdatedAvro.Builder clearAddress() {
      address = null;
      addressBuilder = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserProfileUpdatedAvro build() {
      try {
        UserProfileUpdatedAvro record = new UserProfileUpdatedAvro();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.Long) defaultValue(fields()[0]);
        record.firstName = fieldSetFlags()[1] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.lastName = fieldSetFlags()[2] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.email = fieldSetFlags()[3] ? this.email : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.phoneNumber = fieldSetFlags()[4] ? this.phoneNumber : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.wantsPromotions = fieldSetFlags()[5] ? this.wantsPromotions : (java.lang.Boolean) defaultValue(fields()[5]);
        record.locale = fieldSetFlags()[6] ? this.locale : (java.lang.CharSequence) defaultValue(fields()[6]);
        if (addressBuilder != null) {
          try {
            record.address = this.addressBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("address"));
            throw e;
          }
        } else {
          record.address = fieldSetFlags()[7] ? this.address : (com.allstate.personal_data_service.avro.AddressAvro) defaultValue(fields()[7]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserProfileUpdatedAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserProfileUpdatedAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserProfileUpdatedAvro>
    READER$ = (org.apache.avro.io.DatumReader<UserProfileUpdatedAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.userId);

    out.writeString(this.firstName);

    out.writeString(this.lastName);

    out.writeString(this.email);

    out.writeString(this.phoneNumber);

    out.writeBoolean(this.wantsPromotions);

    out.writeString(this.locale);

    this.address.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readLong();

      this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);

      this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      this.phoneNumber = in.readString(this.phoneNumber instanceof Utf8 ? (Utf8)this.phoneNumber : null);

      this.wantsPromotions = in.readBoolean();

      this.locale = in.readString(this.locale instanceof Utf8 ? (Utf8)this.locale : null);

      if (this.address == null) {
        this.address = new com.allstate.personal_data_service.avro.AddressAvro();
      }
      this.address.customDecode(in);

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readLong();
          break;

        case 1:
          this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);
          break;

        case 2:
          this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);
          break;

        case 3:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 4:
          this.phoneNumber = in.readString(this.phoneNumber instanceof Utf8 ? (Utf8)this.phoneNumber : null);
          break;

        case 5:
          this.wantsPromotions = in.readBoolean();
          break;

        case 6:
          this.locale = in.readString(this.locale instanceof Utf8 ? (Utf8)this.locale : null);
          break;

        case 7:
          if (this.address == null) {
            this.address = new com.allstate.personal_data_service.avro.AddressAvro();
          }
          this.address.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










